### ISSUE TITLE
Kodular - MakeroidStater - Erro de Comunicação em Rede com o Assistente

### ISSUE THREAD

**Issue by ghost** [Kodular/Starter#11]
Após tentar conectar via USB o site apresenta este erro :

> "Um erro interno ocorreu. Denunciar um bug?"

Após alguns minutos este :

> Erro de Comunicação em Rede com o Assistente.
> Reinicie o Assistente e reconecte.

**Comment by arthaswow** [comment]
Same here

**Comment by Frotas101** [comment]
Mesmo reinstalando o driver USB do meu aparelho, não solucionou o problema.
