### ISSUE TITLE
Não consigo instalar o Kodular Stater no Ubuntu 18.04 lts

### ISSUE THREAD

**Issue by Whemerson** [Kodular/Starter#15]
Olá estou tentando instalar o Kodular Stater no meu sistema Ubuntu, porém quando tento instalar o comando: pip install -r requirements.txt, aparece como ERRO o seguinte: 
bash: /home/whemerson/.local/bin/pip: /usr/bin/python: interpretador incorreto: Arquivo ou diretório inexistente

não sei como resolver

**Comment by pavi2410** [comment]
Python is not required to run this now as of v2.0

Simply execute the binaries provided in the releases.
