### ISSUE TITLE
KodularStarter_linux is not executing

### ISSUE THREAD

**Issue by tykoth** [Kodular/Starter#16]
I've downloaded Linux version and chmoded +x, then tried to open executable:

`./KodularStarter_linux: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Can you guys double check this binary?

**Comment by pavi2410** [comment]
You have to install OpenSSL from apt

**Comment by tykoth** [comment]
It's already installed version 2.3.0

**Comment by tykoth** [comment]
I've installed the proper version using an old deb version and works, but now got a lot of errors on prompt and on c.kodular.io panel.

![image](https://github.com/Kodular/Starter/assets/854730/b47421e1-19aa-436d-a493-e7a40d204c15)

Error:
```
>> Starting companion app on device [0061115960] (Keep your phone connected via USB)Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Error type 3
Error: Activity class {io.makeroid.companion/io.makeroid.companion.Screen1} does not exist.
```

**Comment by pavi2410** [comment]
> I've installed the proper version using an old deb version and works, but now got a lot of errors on prompt and on c.kodular.io panel.
> 
> ![image](https://github.com/Kodular/Starter/assets/854730/b47421e1-19aa-436d-a493-e7a40d204c15)
> 
> Error:
> ```
> >> Starting companion app on device [0061115960] (Keep your phone connected via USB)Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
> Error type 3
> Error: Activity class {io.makeroid.companion/io.makeroid.companion.Screen1} does not exist.
> ```

Do you have the Kodular Companion app installed on your phone?

**Comment by tykoth** [comment]
Yes, with Kodular Companion on my phone plugged the problems changed:

```
Kodular Starter v2
OS: linux
ADB path: /tmp/KodularStarter/adb
- - - - - - - - - - - - - - - - - - - - - - 
Running a Vweb app on http://localhost:8004
Hit Ctrl+C to quit.
- - - - - - - - - - - - - - - - - - - - - - 
[INFO] Turn USB debugging on from the Developer Options on your phone
[INFO] Device found = ZF523M37N8
[INFO] Device found = ZF523M37N8
[INFO] Device found = ZF523M37N8
[INFO] Device found = ZF523M37N8
>> Starting companion app on device [ZF523M37N8] (Keep your phone connected via USB)8001
Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```

Achieved this:
```
>> Starting companion app on device [ZF523M37N8] (Keep your phone connected via USB)Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```

After ignored a lot of prompts with "internal erro" message on the app
![image](https://github.com/Kodular/Starter/assets/854730/56b71f1d-691c-44b3-aac4-444612b2cb89)

![image](https://github.com/Kodular/Starter/assets/854730/d84ae919-529f-42ca-8c0c-f114f32e8d89)

But after a lot of insistence o got this error (must wait and cancel a lot of error messages):
![image](https://github.com/Kodular/Starter/assets/854730/be4b69c9-9861-4bdc-b65c-6a90bfd2830e)

**Comment by pavi2410** [comment]
Try out the new GUI version
