### ISSUE TITLE
Mac OS Version?

### ISSUE THREAD

**Issue by lildinti** [Kodular/Starter#2]
Is there a MacOS version?

**Comment by pavi2410** [comment]
Not yet

**Comment by lildinti** [comment]
Thanks Pavi. 
Let me know if I can be of help. Am a devloper and have some experience in MacOS Development. I can work some script or create some app using xcode and/or XOJO. Let me know.
Cheers
Claudio

**Comment by pavi2410** [comment]
@lildinti Could you help us in testing the macOS version of Makeroid Starter?

**Comment by pavi2410** [comment]
Can you please try this version?
https://github.com/Kodular/Starter/suites/247115432/artifacts/74161

**Comment by pavi2410** [comment]
Resolved https://community.kodular.io/t/kodular-starter-v2-0/100337
