### ISSUE TITLE
Kodular | Makeroid Starter - Error on Companion

### ISSUE THREAD

**Issue by ScriiptTeam** [Kodular/Starter#4]
I have Windows 10 (32 bits) - Android Studio & ADB installed. - Makeroid Starter v1.0

Samsung Galaxy S3 Mini - Android 5.1.1 connected.

Error log:

**127.0.0.1 - - [20/Jun/2019 21:51:05] "GET /replstart/47900ab796d0d044 HTTP/1.1" 200 0
Device = 47900ab796d0d044
Starting companion app (Keep your phone connected via USB)
Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Error type 3
Error: Activity class {io.makeroid.companion/io.makeroid.companion.Screen1} does not exist.
127.0.0.1 - - [20/Jun/2019 21:51:14] "GET /replstart/47900ab796d0d044 HTTP/1.1" 200 0
Device = 47900ab796d0d044
Starting companion app (Keep your phone connected via USB)
Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Error type 3
Error: Activity class {io.makeroid.companion/io.makeroid.companion.Screen1} does not exist.**

What I can do? What's the problem?

**Comment by barreeeiroo** [comment]
Are you sure you have the Companion installed in the device ADB is looking for?
It seems like it doesn't find the app

**Comment by ShunsukeHayashi** [comment]
What is this error?

>> Starting companion app on device [1A111FDF6004SB] (Keep your phone connected via USB)Starting: Intent { act=android.intent.action.VIEW cmp=io.makeroid.companion/.Screen1 (has extras) }
Error type 3
Error: Activity class {io.makeroid.companion/io.makeroid.companion.Screen1} does not exist.

**Comment by pavi2410** [comment]
It meant that the app with that package name wasn't installed.
