### ISSUE TITLE
Windows Defender Calles it a virus plz help

### ISSUE THREAD

**Issue by SDWaps** [Kodular/Starter#6]
This is what windows defender says
Category:Trojan:Win32/Zpevdo.b
Description:This program is dangerous and executes commands from an attacker
this is straight from it 
I'm sad :(

**Comment by pavi2410** [comment]
Can you please try this version?
https://github.com/Kodular/Starter/suites/247115432/artifacts/74161

**Comment by meh123456789** [comment]
Thanks

**Comment by KTibow** [comment]
Somebody should change the link over [here](https://starter.kodular.io/), where it says 
![Capture](https://user-images.githubusercontent.com/10727862/69496634-1262e180-0e89-11ea-8677-85ae77cdcb79.PNG) and points to the "virus" Kodular starter.
