### ISSUE TITLE
If anyone have issue running it on Linux here is the solution .

### ISSUE THREAD

**Issue by SalimF** [Kodular/Starter#7]
Hi , first of all  this tools are running on python3  but before running you need to install this Library via `pipe3` 
`sudo pip3 install bottle`

`python3   ./KodularStarter.py`
That's it I hope this added to read me file cheers .

**Comment by barreeeiroo** [comment]
@SalimF it is already specified in `requirements.txt`: https://github.com/Kodular/Starter/blob/master/requirements.txt
When you download any Python application, it is supposed that you run `pip install -r requirements.txt` to install all dependencies

**Comment by SalimF** [comment]
> When you download any Python application, it is supposed that you run `pip install -r requirements.txt` to install all dependencies

Thanks for reply I'm not that experience on python and honest I completely forgot about `requirements.txt`  file , anyway this could confuse people who's try this app first time , because it takes from me many attempts to figure it out .

**Comment by SivagiriVisakan** [comment]
Hi @SalimF !

The instructions for installing are detailed here:
https://docs.kodular.io/guides/live-development/usb/

I hope that these instructions are detailed enough.
If you have any doubts in the instructions on the above link, please do say so that we can try to clarify it.
